# Generated by Django 6.0.3 on 2026-09-15 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0013_alter_loans_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loandraft',
            name='loan_type',
            field=models.CharField(choices=[('Interno', 'Interno'), ('Externo', 'Externo')], default='Interno', max_length=20),
        ),
        migrations.AddField(
            model_name='loandraft',
            name='receptor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='loandraft',
            name='receptor_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='loan_type',
            field=models.CharField(choices=[('Interno', 'Interno'), ('Externo', 'Externo')], default='Interno', max_length=20),
        ),
        migrations.AddField(
            model_name='loans',
            name='receptor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='receptor_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='loandraft',
            name='id_receptor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_prestamos_recibidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loans',
            name='id_receptor_user',
            field=models.ForeignKey(blank=True, db_column='id_receptor_user', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='prestamos_recibidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loans',
            name='state',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Activo', 'Activo'), ('Finalizado', 'Finalizado'), ('Incompleto', 'Incompleto')], default='Pendiente', max_length=20),
        ),
    ]
