# Generated by Django 6.0.3 on 2026-09-22 04:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_category_options_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumablematerial',
            name='entry_date',
            field=models.DateField(default=datetime.date.today, help_text='Fecha en que el material ingresó al inventario.'),
        ),
    ]
