# Generated by Django 6.0.3 on 2026-09-22 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_consumablematerial_entry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Archivo de la cotización (PDF).', upload_to='quotes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(help_text='Material al que pertenece esta cotización.', on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='products.consumablematerial')),
            ],
            options={
                'db_table': 'quotations',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
