# Generated by Django 6.0.3 on 2026-09-22 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Título para identificarla en el selector. Si se deja vacío se usa el nombre del archivo.', max_length=150),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='material',
            field=models.ForeignKey(blank=True, help_text='Material al que está asignada. Null = disponible en la biblioteca.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='products.consumablematerial'),
        ),
    ]
