# Generated by Django 6.0.3 on 2026-09-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_replace_accountable_with_is_accountable'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_consent',
            field=models.BooleanField(default=False, help_text='El titular autorizó el tratamiento de sus datos personales (Ley 1581 de 2012).'),
        ),
        migrations.AddField(
            model_name='user',
            name='data_consent_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se otorgó la autorización.', null=True),
        ),
    ]
