# Generated by Django 6.0.3 on 2026-09-24 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_data_consent_user_data_consent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_session_jti',
            field=models.CharField(blank=True, default=None, help_text='JTI de la sesión activa. Solo una sesión a la vez por usuario.', max_length=64, null=True),
        ),
    ]
