# Generated by Django 6.0.3 on 2026-09-25 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial_audit_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='module',
            field=models.CharField(choices=[('users', 'Usuarios'), ('consumables', 'Materiales Consumibles'), ('returnables', 'Materiales Devolutivos'), ('brands', 'Marcas'), ('loans', 'Préstamos'), ('returns', 'Devoluciones'), ('tasks', 'Tareas'), ('auth', 'Autenticación'), ('permissions', 'Permisos / Grupos'), ('categories', 'Categorías'), ('inventories', 'Nombres de inventario'), ('quotations', 'Cotizaciones')], db_index=True, max_length=30),
        ),
    ]
