# Django settings for sia_api project.
#
# Generated by 'django-admin startproject' using Django 6.0.3.
#
# For more information on this file, see
# https://docs.djangoproject.com/en/6.0/topics/settings/
#
# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/6.0/ref/settings/
import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

def _split_env_list(value):
    # Convierte "a,b,c" en una lista limpia.
    # Nos evita errores por espacios o comas extra.
    return [item.strip() for item in value.split(",") if item.strip()]


# ── Entornos: dev | staging | prod ─────────────────────────────────────
# P0-1: una sola base compartida para todos es riesgo de pérdida de datos.
# DJANGO_ENV decide el nivel de exigencia:
#   dev     → SQLite local por defecto, DEBUG permitido, fallback de SECRET_KEY.
#   staging → espejo de prod con datos desechables, DEBUG=False por defecto.
#   prod    → fail-closed: exige Postgres + SECRET_KEY + hosts reales.
DJANGO_ENV = os.getenv('DJANGO_ENV', 'dev').strip().lower() or 'dev'
if DJANGO_ENV not in ('dev', 'staging', 'prod'):
    raise ImproperlyConfigured(
        f"DJANGO_ENV='{DJANGO_ENV}' no válido. Usa dev, staging o prod."
    )
IS_PROD = DJANGO_ENV == 'prod'
IS_STAGING = DJANGO_ENV == 'staging'

# SECURITY WARNING: don't run with debug turned on in production!
# Activa el modo debug para ver errores detallados.
# En produccion deberia ir en False (en prod se fuerza a False aunque el .env diga True).
if IS_PROD:
    if os.getenv('DEBUG', 'False') == 'True':
        import warnings
        warnings.warn('DEBUG=True ignorado en prod: se fuerza DEBUG=False.')
    DEBUG = False
elif IS_STAGING:
    DEBUG = os.getenv('DEBUG', 'False') == 'True'
else:
    DEBUG = os.getenv('DEBUG', 'True') == 'True'

# SECURITY WARNING: keep the secret key used in production secret!
# Clave secreta usada por Django para firmar sesiones y tokens.
# Fail-closed: en staging/prod es obligatoria y sin ella Django no arranca.
# En dev (local) se usa un fallback solo-dev.
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    if DJANGO_ENV == 'dev' and DEBUG:
        SECRET_KEY = 'dev-secret-key-change-me-in-production'
    else:
        raise ImproperlyConfigured(
            f'SECRET_KEY no está configurada para DJANGO_ENV={DJANGO_ENV}. '
            'Defínela en backend/.env (ver backend/.env.example y docs/entornos.md).'
        )

# Lista de hosts permitidos.
# Si el host no esta aqui, Django rechaza la peticion.
# En prod se exige lista explícita y real (no solo localhost).
ALLOWED_HOSTS = _split_env_list(os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1'))
if DJANGO_ENV == 'dev' and DEBUG:
    for host in ("localhost", "127.0.0.1"):
        if host not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(host)
if IS_PROD and all(h in ('localhost', '127.0.0.1') for h in ALLOWED_HOSTS):
    raise ImproperlyConfigured(
        'ALLOWED_HOSTS en prod no puede ser solo localhost. '
        'Define el dominio real (ej. ALLOWED_HOSTS=api.tu-dominio.edu.co).'
    )


# Detrás de nginx (TLS terminado en el proxy): confiar en
# X-Forwarded-Proto para URLs y CSRF correctos en HTTPS.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'coreapi',
    'django_filters',


    #Apps de django
    'modules.home',
    'modules.users',
    'modules.permissions',
    'modules.products',
    'modules.loans',
    'modules.returns',
    'modules.tasks',
    'modules.audit',
]

AUTH_USER_MODEL = "users.User"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sia_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sia_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Conexion a base de datos tomada del .env.
# dev: SQLite local por defecto. staging/prod: Postgres obligatorio
# (cada entorno con su propio proyecto Supabase; nunca compartir uno solo).
DB_ENGINE = os.getenv('DB_ENGINE') or 'django.db.backends.sqlite3'
if IS_PROD and 'postgresql' not in DB_ENGINE:
    raise ImproperlyConfigured(
        'En prod DB_ENGINE debe ser Postgres (django.db.backends.postgresql). '
        'SQLite no es válido en producción.'
    )
if IS_PROD and not os.getenv('DB_PASSWORD'):
    raise ImproperlyConfigured(
        'En prod DB_PASSWORD es obligatoria. Inyéctala por secreto del PaaS, nunca por git.'
    )
DATABASES = {
    'default': {
        'ENGINE': DB_ENGINE,
        'NAME': os.getenv('DB_NAME') or str(BASE_DIR / 'db.sqlite3'),
        'USER': os.getenv('DB_USER', ''),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', ''),
        'PORT': os.getenv('DB_PORT', ''),
        # Supabase (Postgres + Pooler PgBouncer) exige SSL.
        # Si ENGINE es postgres, agregamos sslmode=require.
        'OPTIONS': {'sslmode': 'require'} if 'postgresql' in DB_ENGINE else {},
        # Con PgBouncer en modo transacción (puerto 6543) no mantener
        # conexiones persistentes: 0 por defecto, ajustable con CONN_MAX_AGE.
        'CONN_MAX_AGE': int(os.getenv('CONN_MAX_AGE', '0')),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


REST_FRAMEWORK={
        'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',

        # Quien valida el token en cada peticion 
        'DEFAULT_AUTHENTICATION_CLASSES': [
            'modules.users.authentication.JWTAuthentication',
        ],

        # Por defecto, TODAS las rutas exigen estar autenticado
        'DEFAULT_PERMISSION_CLASSES': [
            'rest_framework.permissions.IsAuthenticated',
            'modules.users.permissions.NotBlockedByPasswordChange',
        ],

        # Backends de filtrado globales: django-filter para filtros exactos/rango,
        # SearchFilter para búsqueda libre de texto, OrderingFilter para ordenación.
        'DEFAULT_FILTER_BACKENDS': [
            'django_filters.rest_framework.DjangoFilterBackend',
            'rest_framework.filters.SearchFilter',
            'rest_framework.filters.OrderingFilter',
        ],

}

# Origenes permitidos para llamadas desde el navegador.
# Si faltan, el frontend se bloquea por CORS.
CORS_ALLOWED_ORIGINS = _split_env_list(
    os.getenv('CORS_ALLOWED_ORIGINS', 'http://localhost:5173,http://127.0.0.1:5173')
)

# Origenes confiables para CSRF en formularios y POST.
# Si faltan, Django puede responder 403.
CSRF_TRUSTED_ORIGINS = _split_env_list(
    os.getenv('CSRF_TRUSTED_ORIGINS', 'http://localhost:5173,http://127.0.0.1:5173')
)
# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Carpeta donde collectstatic reúne los estáticos para producción
# (los sirve WhiteNoise; STATIC_ROOT ajustable por env).
STATIC_ROOT = os.getenv('STATIC_ROOT') or str(BASE_DIR / 'staticfiles')

# Archivos subidos por usuarios (imagenes, documentos, etc).
# MEDIA_ROOT: carpeta donde se guardan fisicamente en el servidor.
# MEDIA_URL: prefijo de la URL para acceder a ellos desde el navegador.
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# URL base del frontend.
# Se usa para construir enlaces que se envian por correo (ej. reset de contrasena).
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173')

# Configuracion de correo.
# Por defecto usamos el backend de consola: los correos NO se envian,
# se imprimen en la terminal donde corre el servidor. Ideal para desarrollo.
# En produccion, define EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
# junto con EMAIL_HOST, EMAIL_PORT, EMAIL_HOST_USER, EMAIL_HOST_PASSWORD, etc.
EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST     = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT     = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS  = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER     = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')   # App Password de Gmail
DEFAULT_FROM_EMAIL  = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'no-reply@sgi.local')


# Observabilidad: logs a consola (el PaaS los recolecta) con nivel ajustable.
# LOG_LEVEL=DEBUG en local, INFO o WARNING en producción.
LOG_LEVEL = os.getenv('LOG_LEVEL', 'DEBUG' if DEBUG else 'INFO')
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'default': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'default',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
    },
}

# Sentry (opcional): si hay DSN, reporta errores no controlados.
# Sin DSN no hace nada. Requiere `sentry-sdk` (ver pyproject.toml).
SENTRY_DSN = os.getenv('SENTRY_DSN', '')
if SENTRY_DSN:
    try:
        import sentry_sdk
        sentry_sdk.init(
            dsn=SENTRY_DSN,
            send_default_pii=False,
            traces_sample_rate=0.0,
        )
    except ImportError:  # pragma: no cover - SDK no instalado
        import logging
        logging.getLogger(__name__).warning(
            'SENTRY_DSN definido pero sentry-sdk no está instalado.'
        )
