# Generated by Django 6.0.3 on 2026-09-30 00:34
# Fase 1 del sistema dinámico de roles: peso de autoridad por permiso.
# El peso es SOLO métrica (no decide jerarquía). La política de tiers vive
# en modules/permissions/authority.py y se reutiliza aquí para sembrar
# los permisos existentes.

from django.db import migrations, models

from modules.permissions.authority import permission_weight_for


def seed_weights(apps, schema_editor):
    Permission = apps.get_model("permissions", "Permission")
    for perm in Permission.objects.all().only("id", "codename"):
        weight = permission_weight_for(perm.codename)
        if weight != 10:
            Permission.objects.filter(pk=perm.pk).update(weight=weight)


def unseed_weights(apps, schema_editor):
    Permission = apps.get_model("permissions", "Permission")
    Permission.objects.all().update(weight=10)


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0016_add_notification_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='weight',
            field=models.PositiveIntegerField(default=10, help_text='Peso de autoridad (Fase 1: solo métrica de análisis, no decide jerarquía). Solo lo edita el Primigenio; cambios auditados.'),
        ),
        migrations.RunPython(seed_weights, unseed_weights),
    ]
