# Generated by Django 6.0.3 on 2026-09-30 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0017_permission_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='authority_ceiling',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Techo de autoridad estimada del nivel. Vacío = sin techo.', null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='is_system',
            field=models.BooleanField(default=False, help_text='Si es rol de sistema: inmutable por API. Reemplaza el nombre hardcodeado.'),
        ),
        migrations.AddField(
            model_name='group',
            name='level',
            field=models.PositiveIntegerField(default=900, help_text='Nivel jerárquico (menor = más poder). Roles nuevos nacen abajo (900).'),
        ),
        migrations.AddField(
            model_name='group',
            name='template_role',
            field=models.ForeignKey(blank=True, help_text='Rol usado como plantilla al crear este (referencia, sin herencia viva).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templated_roles', to='permissions.group'),
        ),
    ]
