# Generated by Django 6.0.3 on 2026-09-30 00:45
# Fase 2 del sistema dinámico de roles: niveles, flags de sistema y techos
# de autoridad de los 4 grupos actuales. Techos medidos sobre la autoridad
# real (SADMIN 2520, ADMIN 2060, INST 720, INV 270) con holgura para crecer.
# SADMIN queda sin techo: solo el Primigenio opera a ese nivel.

from django.db import migrations


SYSTEM_LEVELS = {
    # nombre: (level, authority_ceiling)
    "SADMIN": (100, None),
    "ADMIN": (200, 2600),
    "INST": (300, 1000),
    "INV": (400, 500),
}


def assign_levels(apps, schema_editor):
    Group = apps.get_model("permissions", "Group")
    for name, (level, ceiling) in SYSTEM_LEVELS.items():
        Group.objects.filter(name__iexact=name).update(
            level=level, is_system=True, authority_ceiling=ceiling
        )


def unassign_levels(apps, schema_editor):
    Group = apps.get_model("permissions", "Group")
    for name in SYSTEM_LEVELS:
        Group.objects.filter(name__iexact=name).update(
            level=900, is_system=False, authority_ceiling=None
        )


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0018_group_authority_ceiling_group_is_system_group_level_and_more'),
    ]

    operations = [
        migrations.RunPython(assign_levels, unassign_levels),
    ]
