# Generated by Django 6.0.3 on 2026-09-30 00:55
# Fase 3 del sistema dinámico de roles: INST e INV pueden listar usuarios
# (mismo nivel o inferior, filtrado por visible_users_queryset).
# Solo lectura: list_users + view_user. Sin crear/editar/exportar.

from django.db import migrations


LISTING_CODES = ["list_users", "view_user"]
TARGET_GROUPS = ["INST", "INV"]


def grant_listing(apps, schema_editor):
    Group = apps.get_model("permissions", "Group")
    Permission = apps.get_model("permissions", "Permission")
    GroupPermission = apps.get_model("permissions", "GroupPermission")
    for group_name in TARGET_GROUPS:
        try:
            group = Group.objects.get(name=group_name)
        except Group.DoesNotExist:
            continue
        for codename in LISTING_CODES:
            try:
                permission = Permission.objects.get(codename=codename)
            except Permission.DoesNotExist:
                continue
            GroupPermission.objects.get_or_create(group=group, permission=permission)


def ungrant_listing(apps, schema_editor):
    Group = apps.get_model("permissions", "Group")
    Permission = apps.get_model("permissions", "Permission")
    GroupPermission = apps.get_model("permissions", "GroupPermission")
    GroupPermission.objects.filter(
        group__name__in=TARGET_GROUPS, permission__codename__in=LISTING_CODES
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0019_assign_group_levels'),
    ]

    operations = [
        migrations.RunPython(grant_listing, ungrant_listing),
    ]
