# Generated by Django 6.0.3 on 2026-09-30 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0020_grant_user_listing_inst_inv'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCambioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE_ROLE', 'Crear rol'), ('UPDATE_ROLE_PERMS', 'Modificar permisos de rol')], max_length=24)),
                ('payload', models.JSONField(default=dict)),
                ('content_hash', models.CharField(blank=True, default='', help_text='SHA256 canónico del contenido al enviar (anti A→A+).', max_length=64)),
                ('status', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('EXPIRADA', 'Expirada'), ('CANCELADA', 'Cancelada'), ('ACTIVA', 'Activa')], default='BORRADOR', max_length=12)),
                ('security_level', models.CharField(blank=True, default='', help_text='N1/N2/N3 calculado al enviar.', max_length=2)),
                ('reason', models.TextField(blank=True, help_text='Motivo de la solicitud.')),
                ('decision_reason', models.TextField(blank=True, help_text='Motivo de la decisión.')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, help_text='Quien aprobó o rechazó. Debe ser estrictamente superior.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_decididas', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='Rol objetivo (null en CREATE_ROLE).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='permissions.group')),
                ('requester', models.ForeignKey(help_text='Quien propone la elevación. No puede aprobar la propia.', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de cambio de rol',
                'verbose_name_plural': 'Solicitudes de cambio de rol',
                'db_table': 'solicitudes_cambio_rol',
                'ordering': ['-created_at'],
            },
        ),
    ]
