# Generated by Django 6.0.3 on 2026-09-30 04:49
# Fase 5a: permiso approve_elevation (decidir solicitudes N2/N3).
# Se otorga a SADMIN. Peso 150 (crítico): solo el Primigenio lo reasigna.

from django.db import migrations

from modules.permissions.authority import permission_weight_for


def seed_approve_elevation(apps, schema_editor):
    Permission = apps.get_model("permissions", "Permission")
    Group = apps.get_model("permissions", "Group")
    GroupPermission = apps.get_model("permissions", "GroupPermission")
    permission, _ = Permission.objects.get_or_create(
        codename="approve_elevation",
        defaults={
            "name": "Aprobar elevaciones",
            "description": "Decidir solicitudes de elevación de roles (N2/N3).",
            "weight": permission_weight_for("approve_elevation"),
        },
    )
    try:
        group = Group.objects.get(name="SADMIN")
    except Group.DoesNotExist:
        return
    GroupPermission.objects.get_or_create(group=group, permission=permission)


def unseed_approve_elevation(apps, schema_editor):
    Permission = apps.get_model("permissions", "Permission")
    GroupPermission = apps.get_model("permissions", "GroupPermission")
    Permission.objects.filter(codename="approve_elevation").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0021_solicitudcambiorol'),
    ]

    operations = [
        migrations.RunPython(seed_approve_elevation, unseed_approve_elevation),
    ]
