# Generated by Django 6.0.3 on 2026-09-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0022_seed_approve_elevation'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppermission',
            name='scope',
            field=models.CharField(choices=[('SELF', 'Lo propio'), ('ALL', 'Todo')], default='SELF', help_text='Alcance: SELF (lo propio) o ALL (todo). Default seguro.', max_length=4),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='scope',
            field=models.CharField(choices=[('SELF', 'Lo propio'), ('ALL', 'Todo')], default='SELF', help_text='Alcance: SELF (lo propio) o ALL (todo). Default seguro.', max_length=4),
        ),
    ]
