# Generated by Django 6.0.3 on 2026-09-30 05:28
# Fase 6 (alcance): conserva el comportamiento actual al estrenar scope.
# - Permisos sin objeto (marcas, categorías...): ALL siempre.
# - Préstamos/tareas: SADMIN y ADMIN → ALL (equivale al chequeo anterior
#   por superusuario/nombre de grupo); INST/INV y resto → SELF (lo propio).
# - Asignaciones directas: superusuarios → ALL; resto igual que grupos.

from django.db import migrations

from modules.permissions.ranking import SCOPED_PERMISSIONS


def backfill_scope(apps, schema_editor):
    Group = apps.get_model("permissions", "Group")
    GroupPermission = apps.get_model("permissions", "GroupPermission")
    UserPermission = apps.get_model("permissions", "UserPermission")
    User = apps.get_model("users", "User")

    scoped = set(SCOPED_PERMISSIONS)
    for gp in GroupPermission.objects.select_related("group", "permission").all():
        if gp.permission.codename not in scoped:
            scope = "ALL"
        elif gp.group.level <= 200:
            scope = "ALL"
        else:
            scope = "SELF"
        if gp.scope != scope:
            gp.scope = scope
            gp.save(update_fields=["scope"])

    superuser_ids = set(
        User.objects.filter(is_superuser=True).values_list("id", flat=True)
    )
    for up in UserPermission.objects.select_related("user", "permission").all():
        if up.permission.codename not in scoped:
            scope = "ALL"
        elif up.user_id in superuser_ids:
            scope = "ALL"
        else:
            scope = "SELF"
        if up.scope != scope:
            up.scope = scope
            up.save(update_fields=["scope"])


def unbackfill_scope(apps, schema_editor):
    GroupPermission = apps.get_model("permissions", "GroupPermission")
    UserPermission = apps.get_model("permissions", "UserPermission")
    GroupPermission.objects.all().update(scope="SELF")
    UserPermission.objects.all().update(scope="SELF")


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0023_grouppermission_scope_userpermission_scope'),
    ]

    operations = [
        migrations.RunPython(backfill_scope, unbackfill_scope),
    ]
