# Generated by Django 6.0.3 on 2026-09-24 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_assignment_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_task_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='requires_evidence',
            field=models.BooleanField(default=False, help_text='Exige evidencias (archivos/fotos) al finalizar la tarea.'),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='state',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En progreso', 'En progreso'), ('En revisión', 'En revisión'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='TaskEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='task_evidence/%Y/%m/')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='tasks.taskassignment')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_evidences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evidencia de tarea',
                'verbose_name_plural': 'Evidencias de tareas',
                'db_table': 'EvidenciasTareas',
            },
        ),
    ]
